# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      #steup node 22.11
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.11'

      # Step 3: Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build the project
        run: pnpm run build

      - name: Run tests
        env:
          MONGODB_HOST: ${{ secrets.MONGODB_HOST }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
        run: pnpm test

      # deploy in to heroku using heroku registry
      #  Log in to Docker Hub
      - name: Log in to Docker Hub
        run: docker login --username=_ --password=${{ secrets.HEROKU_API_KEY }} registry.heroku.com

        #  Stop the previous running container (if any) on Heroku
      - name: Stop previous Heroku container
        run: |
          heroku ps:stop web --app ${{ secrets.HEROKU_APP_NAME }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

        #  Build the Docker image
      - name: Build Docker image
        run: docker build --build-arg MONGODB_HOST_ARG=${{ secrets.MONGODB_HOST }} JWT_SECRET_ARG=${{ secrets.JWT_SECRET }} JWT_EXPIRATION_ARG=${{ secrets.JWT_EXPIRATION }} -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web .

        #  Push the Docker image to Heroku
      - name: Push Docker image to Heroku
        run: docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

        # Ensure the Heroku stack is set to container
      - name: Set Heroku stack to container
        run: heroku stack:set container --app ${{ secrets.HEROKU_APP_NAME }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

        #  Release the image on Heroku
      - name: Release on Heroku
        run: |
          heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
